#!/bin/bash

path="."

if [ $# -ne 0 ]; then
	path=$1
fi

echo -e ""
echo -e "\033[1;33mTest 1: help\033[0m"
$path/files_worker --help
echo -e ""

echo -e "\033[1;33mTest 2: Empty command line argument list\033[0m"
$path/files_worker
echo -e ""

echo -e "\033[1;33mTest 3: Not exist file\033[0m"
$path/files_worker $path/not_ex_file
echo -e ""

echo -e "\033[1;33mTest 4: Standart work\033[0m"
rm -f $path/data_file
touch $path/data_file
chmod u=rwx $path/data_file
echo "Hello world" >> $path/data_file
echo "Hello world" >> $path/data_file
echo "Hello world" >> $path/data_file
$path/files_worker $path/data_file
echo -e ""

rm -f $path/data_file
