#!/bin/bash

path="."

if [ $# -ne 0 ]; then
	path=$1
fi

echo -e ""
echo -e "\033[1;33mTest 1: Standart work\033[0m"
$path/processes_worker &
sleep 1 && ps
ps axf | grep processes_worke | grep -v grep | awk '{ system("kill -9 " $1)}'
echo -e ""
