#!/bin/bash

path="."

if [ $# -ne 0 ]; then
	path=$1
fi

echo -e ""
echo -e "\033[1;33mTest 1: Standart work\033[0m"
rm $path/data_file
touch $path/data_file
chmod 777 $path/data_file
$path/pipes_worker $path/data_file
echo -e ""