#!/bin/bash

path="."

if [ $# -ne 0 ]; then
	path=$1
fi

echo -e ""
echo -e "\033[1;33mTest 1: Standart work\033[0m"
$path/stat 2
echo -e ""
$path/write 2 100 hello
$path/stat 2
echo -e ""
$path/read 2 100
echo -e ""
$path/stat 2
echo -e ""
$path/remove 2
echo -e ""