#!/bin/bash

path="."

if [ $# -ne 0 ]; then
        path=$1
fi

echo -e ""
echo -e "\033[1;33mTest 1: help\033[0m"
$path/files_worker --help
echo -e ""

echo -e "\033[1;33mTest 2: Empty command line argument list\033[0m"
$path/files_worker
echo -e ""

echo -e "\033[1;33mTest 3: Not exist file\033[0m"
$path/files_worker $path/not_ex_file
echo -e ""

echo -e "\033[1;33mTest 4: Standart work: One file\033[0m"
rm -f $path/data_file1
touch $path/data_file1
chmod u=rwx $path/data_file1
echo "Hello world" >> $path/data_file1
$path/files_worker $path/data_file1
echo -e ""

echo -e "\033[1;33mTest 5: Standart work: Two files\033[0m"
rm -f $path/data_file1
rm -f $path/data_file2

touch $path/data_file1
touch $path/data_file2

chmod u=rwx $path/data_file1
chmod u=rwx $path/data_file2

echo "Hello world" >> $path/data_file1
echo "Hello world" >> $path/data_file2
echo "Hello world" >> $path/data_file2
$path/files_worker $path/data_file1 $path/data_file2
echo -e ""

echo -e "\033[1;33mTest 5: Standart work: Three files\033[0m"
rm -f $path/data_file1
rm -f $path/data_file2
rm -f $path/data_file3

touch $path/data_file1
touch $path/data_file2
touch $path/data_file3

chmod u=rwx $path/data_file1
chmod u=rwx $path/data_file2
chmod u=rwx $path/data_file3

echo "Hello world" >> $path/data_file1
echo "Hello world" >> $path/data_file2
echo "Hello world" >> $path/data_file2
echo "Hello world" >> $path/data_file3
echo "Hello world" >> $path/data_file3
echo "Hello world" >> $path/data_file3
$path/files_worker $path/data_file1 $path/data_file2 $path/data_file3
echo -e ""

rm -f $path/data_file1
rm -f $path/data_file2
rm -f $path/data_file3
