#!/bin/bash

path="."

if [ $# -ne 0 ]; then
	path=$1
fi

echo -e ""
echo -e "\033[1;33mTest 1: Standart work\033[0m"
$path/stat 5
echo -e ""
$path/write 5 100 hellohellohellohello
$path/stat 5
echo -e ""
$path/remove 5
echo -e ""